---
name: Promote
on: workflow_dispatch
jobs:
  promote:
    name: Promote container image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Update Production Version
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        cp .github/development-version.txt .github/production-version.txt
        git add .github/production-version.txt
        git commit -m "update production version: $(cat .github/production-version.txt)"
        git pull --rebase
        git push
